language: ruby
rvm:
  - '2.6'
  - '2.5'
matrix:
  allow_failures:
    - rvm: '2.5'
script: |
  bad=""
  for f in *.rb; do
    if ! ruby -c $f; then
      bad="$bad $f"
    fi
  done
  if [ -n "$bad" ]; then
    echo "bad: $bad"
    exit 1
  fi
